services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 5432:5432
    volumes:
        - ./postgres-data:/var/lib/postgresql/data
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    ports: 
        - 8080:8080
    volumes: 
        - ravendb-data:/data
volumes:
    pgdata:
    ravendb-data: