services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=postgrespw
    ports:
        - 5432:5432
    volumes:
        - /var/lib/postgresql/data
  ravendb-node1:
    image: ravendb/ravendb:latest
    ports: 
        - 8080:8080
        - 38888:38889
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
    volumes: 
        - /var/lib/ravendb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
  auction-svc:
    image: bartmint/auction-svc:latest
    build:
        context: .
        dockerfile: src/AuctionService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=auctions
        - IdentityServiceUrl=http://identity-svc
    ports:
        - 7001:80
    depends_on:
        - postgres
        - rabbitmq
  search-service-svc:
    image: bartmint/search-service-svc:latest
    build:
        context: .
        dockerfile: src/SearchService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__RavenDbConnection=Url=http://ravendb-node1:8080;Database=search-service-db
        - AuctionServiceUrl=http://auction-svc
    ports:
        - 7002:80
    depends_on:
        - ravendb-node1
        - rabbitmq
  identity-svc:
    image: bartmint/identity-svc:latest
    build:
        context: .
        dockerfile: src/IdentityService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
        - 5000:80
    depends_on:
        - postgres
