// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20240317190254_Outbox")]
    partial class Outbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentHighBid")
                        .HasColumnType("integer");

                    b.Property<int>("ReservePrice")
                        .HasColumnType("integer");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SoldAmount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Winner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afbee524-5972-4075-8800-7d1f9d7b0a0c"),
                            AuctionEnd = new DateTime(2024, 3, 27, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4892),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4879),
                            ReservePrice = 20000,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4882)
                        },
                        new
                        {
                            Id = new Guid("c8c3ec17-01bf-49db-82aa-1ef80b833a9f"),
                            AuctionEnd = new DateTime(2024, 5, 16, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4905),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4903),
                            ReservePrice = 90000,
                            Seller = "alice",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4904)
                        },
                        new
                        {
                            Id = new Guid("bbab4d5a-8565-48b1-9450-5ac2a5c4a654"),
                            AuctionEnd = new DateTime(2024, 3, 21, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4910),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4909),
                            ReservePrice = 0,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4909)
                        },
                        new
                        {
                            Id = new Guid("155225c1-4448-4066-9886-6786536e05ea"),
                            AuctionEnd = new DateTime(2024, 3, 7, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4914),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4911),
                            ReservePrice = 50000,
                            Seller = "tom",
                            Status = 2,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4912)
                        },
                        new
                        {
                            Id = new Guid("466e4744-4dc5-4987-aae0-b621acfc5e39"),
                            AuctionEnd = new DateTime(2024, 4, 16, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4917),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4915),
                            ReservePrice = 20000,
                            Seller = "alice",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4915)
                        },
                        new
                        {
                            Id = new Guid("dc1e4071-d19d-459b-b848-b5c3cd3d151f"),
                            AuctionEnd = new DateTime(2024, 5, 1, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4922),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4921),
                            ReservePrice = 20000,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4921)
                        },
                        new
                        {
                            Id = new Guid("47111973-d176-4feb-848d-0ea22641c31a"),
                            AuctionEnd = new DateTime(2024, 3, 30, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4925),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4923),
                            ReservePrice = 150000,
                            Seller = "alice",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4924)
                        },
                        new
                        {
                            Id = new Guid("6a5011a1-fe1f-47df-9a32-b5346b289391"),
                            AuctionEnd = new DateTime(2024, 4, 5, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4927),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4926),
                            ReservePrice = 0,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4926)
                        },
                        new
                        {
                            Id = new Guid("40490065-dac7-46b6-acc4-df507e0d6570"),
                            AuctionEnd = new DateTime(2024, 4, 6, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4930),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4928),
                            ReservePrice = 20000,
                            Seller = "tom",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4929)
                        },
                        new
                        {
                            Id = new Guid("3659ac24-29dd-407a-81f5-ecfe6f924b9b"),
                            AuctionEnd = new DateTime(2024, 5, 4, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4934),
                            CreatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4932),
                            ReservePrice = 20000,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 19, 2, 54, 28, DateTimeKind.Utc).AddTicks(4932)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0720b68f-ecf1-4052-be2f-4202d76da414"),
                            AuctionId = new Guid("afbee524-5972-4075-8800-7d1f9d7b0a0c"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/06/16/32/car-1376190_960_720.jpg",
                            Make = "Ford",
                            Mileage = 50000,
                            Model = "GT",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("824cf5f4-5313-4f98-85ca-d5b5c7eec7d4"),
                            AuctionId = new Guid("c8c3ec17-01bf-49db-82aa-1ef80b833a9f"),
                            Color = "Black",
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/05/29/00/43/car-49278_960_720.jpg",
                            Make = "Bugatti",
                            Mileage = 15035,
                            Model = "Veyron",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("0d752e09-133a-4240-ba77-9b28ec1e954f"),
                            AuctionId = new Guid("bbab4d5a-8565-48b1-9450-5ac2a5c4a654"),
                            Color = "Black",
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/11/02/13/02/car-63930_960_720.jpg",
                            Make = "Ford",
                            Mileage = 65125,
                            Model = "Mustang",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("4eb3359a-d9f2-416a-ae81-71a64d0df9b8"),
                            AuctionId = new Guid("155225c1-4448-4066-9886-6786536e05ea"),
                            Color = "Silver",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/04/17/22/10/mercedes-benz-1335674_960_720.png",
                            Make = "Mercedes",
                            Mileage = 15001,
                            Model = "SLK",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("26545af2-5d88-4f85-9b4f-53f863de673d"),
                            AuctionId = new Guid("466e4744-4dc5-4987-aae0-b621acfc5e39"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/31/05/47/bmw-2699538_960_720.jpg",
                            Make = "BMW",
                            Mileage = 90000,
                            Model = "X1",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("927cc1db-91c5-4f92-9cd3-a22834a2b5ec"),
                            AuctionId = new Guid("dc1e4071-d19d-459b-b848-b5c3cd3d151f"),
                            Color = "Red",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/11/09/01/49/ferrari-458-spider-2932191_960_720.jpg",
                            Make = "Ferrari",
                            Mileage = 50000,
                            Model = "Spider",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("a24b5ad3-214c-4e36-8bb6-88361def9495"),
                            AuctionId = new Guid("47111973-d176-4feb-848d-0ea22641c31a"),
                            Color = "Red",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/11/08/14/39/ferrari-f430-2930661_960_720.jpg",
                            Make = "Ferrari",
                            Mileage = 5000,
                            Model = "F-430",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("22493770-9c44-483a-88c1-1d235bec3556"),
                            AuctionId = new Guid("6a5011a1-fe1f-47df-9a32-b5346b289391"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/12/26/20/50/audi-r8-4721217_960_720.jpg",
                            Make = "Audi",
                            Mileage = 10050,
                            Model = "R8",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("03bdbccb-9330-46df-a320-86a0594ecf95"),
                            AuctionId = new Guid("40490065-dac7-46b6-acc4-df507e0d6570"),
                            Color = "Black",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/01/15/06/audi-1636320_960_720.jpg",
                            Make = "Audi",
                            Mileage = 25400,
                            Model = "TT",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("38a90df5-9a95-45a5-8e2e-610284009221"),
                            AuctionId = new Guid("3659ac24-29dd-407a-81f5-ecfe6f924b9b"),
                            Color = "Rust",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/02/19/47/vintage-2573090_960_720.jpg",
                            Make = "Ford",
                            Mileage = 150150,
                            Model = "Model T",
                            Year = 1938
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasAlternateKey("MessageId", "ConsumerId");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Infrastructure.Entities.Subject", b =>
                {
                    b.HasOne("Infrastructure.Entities.Auction", "Auction")
                        .WithOne("Subject")
                        .HasForeignKey("Infrastructure.Entities.Subject", "AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Infrastructure.Entities.Auction", b =>
                {
                    b.Navigation("Subject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
