// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20240315204233_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AuctionEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentHighBid")
                        .HasColumnType("integer");

                    b.Property<int>("ReservePrice")
                        .HasColumnType("integer");

                    b.Property<string>("Seller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SoldAmount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Winner")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afbee524-5972-4075-8800-7d1f9d7b0a0c"),
                            AuctionEnd = new DateTime(2024, 3, 25, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5111),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5096),
                            ReservePrice = 20000,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5097)
                        },
                        new
                        {
                            Id = new Guid("c8c3ec17-01bf-49db-82aa-1ef80b833a9f"),
                            AuctionEnd = new DateTime(2024, 5, 14, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5119),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5118),
                            ReservePrice = 90000,
                            Seller = "alice",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5118)
                        },
                        new
                        {
                            Id = new Guid("bbab4d5a-8565-48b1-9450-5ac2a5c4a654"),
                            AuctionEnd = new DateTime(2024, 3, 19, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5122),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5120),
                            ReservePrice = 0,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5121)
                        },
                        new
                        {
                            Id = new Guid("155225c1-4448-4066-9886-6786536e05ea"),
                            AuctionEnd = new DateTime(2024, 3, 5, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5124),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5122),
                            ReservePrice = 50000,
                            Seller = "tom",
                            Status = 2,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5123)
                        },
                        new
                        {
                            Id = new Guid("466e4744-4dc5-4987-aae0-b621acfc5e39"),
                            AuctionEnd = new DateTime(2024, 4, 14, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5126),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5125),
                            ReservePrice = 20000,
                            Seller = "alice",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5125)
                        },
                        new
                        {
                            Id = new Guid("dc1e4071-d19d-459b-b848-b5c3cd3d151f"),
                            AuctionEnd = new DateTime(2024, 4, 29, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5131),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5129),
                            ReservePrice = 20000,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5129)
                        },
                        new
                        {
                            Id = new Guid("47111973-d176-4feb-848d-0ea22641c31a"),
                            AuctionEnd = new DateTime(2024, 3, 28, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5133),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5132),
                            ReservePrice = 150000,
                            Seller = "alice",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5132)
                        },
                        new
                        {
                            Id = new Guid("6a5011a1-fe1f-47df-9a32-b5346b289391"),
                            AuctionEnd = new DateTime(2024, 4, 3, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5135),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5134),
                            ReservePrice = 0,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5134)
                        },
                        new
                        {
                            Id = new Guid("40490065-dac7-46b6-acc4-df507e0d6570"),
                            AuctionEnd = new DateTime(2024, 4, 4, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5137),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5136),
                            ReservePrice = 20000,
                            Seller = "tom",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5136)
                        },
                        new
                        {
                            Id = new Guid("3659ac24-29dd-407a-81f5-ecfe6f924b9b"),
                            AuctionEnd = new DateTime(2024, 5, 2, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5140),
                            CreatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5139),
                            ReservePrice = 20000,
                            Seller = "bob",
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 15, 20, 42, 33, 130, DateTimeKind.Utc).AddTicks(5139)
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3bce1564-78be-4224-9cd8-4d977c8f54ed"),
                            AuctionId = new Guid("afbee524-5972-4075-8800-7d1f9d7b0a0c"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/05/06/16/32/car-1376190_960_720.jpg",
                            Make = "Ford",
                            Mileage = 50000,
                            Model = "GT",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("e8645886-60eb-4863-b4c4-ed4d77ddd632"),
                            AuctionId = new Guid("c8c3ec17-01bf-49db-82aa-1ef80b833a9f"),
                            Color = "Black",
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/05/29/00/43/car-49278_960_720.jpg",
                            Make = "Bugatti",
                            Mileage = 15035,
                            Model = "Veyron",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("f0c5592d-06e2-449d-84ed-4ee70dd672f6"),
                            AuctionId = new Guid("bbab4d5a-8565-48b1-9450-5ac2a5c4a654"),
                            Color = "Black",
                            ImageUrl = "https://cdn.pixabay.com/photo/2012/11/02/13/02/car-63930_960_720.jpg",
                            Make = "Ford",
                            Mileage = 65125,
                            Model = "Mustang",
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("8a646784-3d57-44e3-84f7-c5b2c1b25e8b"),
                            AuctionId = new Guid("155225c1-4448-4066-9886-6786536e05ea"),
                            Color = "Silver",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/04/17/22/10/mercedes-benz-1335674_960_720.png",
                            Make = "Mercedes",
                            Mileage = 15001,
                            Model = "SLK",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("dc545b37-0b34-4e24-8de0-b0d171549c10"),
                            AuctionId = new Guid("466e4744-4dc5-4987-aae0-b621acfc5e39"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/31/05/47/bmw-2699538_960_720.jpg",
                            Make = "BMW",
                            Mileage = 90000,
                            Model = "X1",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("4b0371fa-d648-4dc6-8ca1-4f78d8fd5da6"),
                            AuctionId = new Guid("466e4744-4dc5-4987-aae0-b621acfc5e39"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/31/05/47/bmw-2699538_960_720.jpg",
                            Make = "BMW",
                            Mileage = 90000,
                            Model = "X1",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("9c84c8e2-f615-436c-b160-d84a6b20b0ee"),
                            AuctionId = new Guid("dc1e4071-d19d-459b-b848-b5c3cd3d151f"),
                            Color = "Red",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/11/09/01/49/ferrari-458-spider-2932191_960_720.jpg",
                            Make = "Ferrari",
                            Mileage = 50000,
                            Model = "Spider",
                            Year = 2015
                        },
                        new
                        {
                            Id = new Guid("54e89752-a65a-4401-b2c2-8277c0dad1bb"),
                            AuctionId = new Guid("47111973-d176-4feb-848d-0ea22641c31a"),
                            Color = "Red",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/11/08/14/39/ferrari-f430-2930661_960_720.jpg",
                            Make = "Ferrari",
                            Mileage = 5000,
                            Model = "F-430",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("13610ad9-1a31-4962-86a3-ccd3930f1f35"),
                            AuctionId = new Guid("6a5011a1-fe1f-47df-9a32-b5346b289391"),
                            Color = "White",
                            ImageUrl = "https://cdn.pixabay.com/photo/2019/12/26/20/50/audi-r8-4721217_960_720.jpg",
                            Make = "Audi",
                            Mileage = 10050,
                            Model = "R8",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("2feed3f2-8404-4a73-9aad-f6ce78464f31"),
                            AuctionId = new Guid("40490065-dac7-46b6-acc4-df507e0d6570"),
                            Color = "Black",
                            ImageUrl = "https://cdn.pixabay.com/photo/2016/09/01/15/06/audi-1636320_960_720.jpg",
                            Make = "Audi",
                            Mileage = 25400,
                            Model = "TT",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("c3a84bb9-a2d2-452f-8e32-dacfae34119c"),
                            AuctionId = new Guid("3659ac24-29dd-407a-81f5-ecfe6f924b9b"),
                            Color = "Rust",
                            ImageUrl = "https://cdn.pixabay.com/photo/2017/08/02/19/47/vintage-2573090_960_720.jpg",
                            Make = "Ford",
                            Mileage = 150150,
                            Model = "Model T",
                            Year = 1938
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Subject", b =>
                {
                    b.HasOne("Infrastructure.Entities.Auction", "Auction")
                        .WithOne("Subject")
                        .HasForeignKey("Infrastructure.Entities.Subject", "AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Infrastructure.Entities.Auction", b =>
                {
                    b.Navigation("Subject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
